services:
  ollama:
    volumes:
      - v1:/ollama
    container_name: ollama1
    pull_policy: always
    tty: true
    restart: unless-stopped
    build: ollama
    ports:
      - 11435:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/usr/bin/bash", "/my_llm_model.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  v1:
    driver: local
